export const uiCopy = {
  common: {
    loading: "加载中…",
    working: "处理中…",
    dismissNotification: "关闭通知",
    continue: "继续",
    save: "保存",
    cancel: "取消",
    search: "搜索",
  },
  auth: {
    signInTitle: "登录 Paperclip",
    signUpTitle: "创建你的 Paperclip 账户",
    signInDescription: "使用邮箱和密码登录当前实例。",
    signUpDescription: "为当前实例创建账户。v1 暂不需要邮箱验证。",
    name: "姓名",
    email: "邮箱",
    password: "密码",
    signInAction: "登录",
    signUpAction: "创建账户",
    needAccount: "还没有账户？",
    haveAccount: "已经有账户了？",
    createOne: "立即创建",
    switchToSignIn: "去登录",
    fillRequired: "请填写所有必填项。",
    failed: "登录或注册失败",
  },
  sidebar: {
    selectCompany: "选择公司",
    newIssue: "新建任务 / Issue",
    dashboard: "仪表盘",
    inbox: "收件箱",
    work: "工作区",
    issues: "任务 / Issues",
    routines: "例行任务 / Routines",
    goals: "目标 / Goals",
    company: "公司",
    org: "组织架构 / Org",
    skills: "技能 / Skills",
    costs: "成本 / Costs",
    activity: "活动 / Activity",
    settings: "设置",
    beta: "测试版",
  },
  empty: {
    defaultTitle: "这里还没有内容",
    defaultAction: "继续",
  },
} as const;
